/*
 * Adapted from The MIT License (MIT)
 *
 * Copyright (c) 2020-2020 DaPorkchop_
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
 * is furnished to do so, subject to the following conditions:
 *
 * Any persons and/or organizations using this software must include the above copyright notice and this permission notice,
 * provide sufficient credit to the original authors of the project (IE: DaPorkchop_), as well as provide a link to the original project.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 */
plugins {
    id 'java'
    id 'maven-publish'
}

ext {
    // General configuration
    javaVersion = JavaVersion.VERSION_11
    programVersion = '0.0.11-SNAPSHOT'

    // Dependency versions
    junitVersion = '4.13.2'
    lombokVersion = '1.18.46'
    leveldbVersion = '1.1.0'
    guavaVersion = '32.0.1-jre'
    nettyVersion = '4.2.12.Final'
    porklibVersion = '0.5.9-SNAPSHOT'
    snappyVersion = '0.5'
}

group = 'dev.mot.leveldb'
version = programVersion

def mavenDeployUsername = findProperty('MAVEN_DEPLOY_USERNAME') ?: System.getenv('MAVEN_DEPLOY_USERNAME')
def mavenDeployPassword = findProperty('MAVEN_DEPLOY_PASSWORD') ?: System.getenv('MAVEN_DEPLOY_PASSWORD')
def isSnapshotVersion = version.toString().endsWith('SNAPSHOT')
def publishRepositoryName = isSnapshotVersion ? 'mot-repo-snapshot' : 'mot-repo-release'
def publishRepositoryUrl = isSnapshotVersion ? 'https://repo.mot.dev/repository/maven-snapshots/' : 'https://repo.mot.dev/repository/maven-releases/'

java {
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

repositories {
    maven {
        name = 'mot-repo-release'
        url = 'https://repo.mot.dev/repository/maven-releases/'
    }
    maven {
        name = 'mot-repo-snapshot'
        url = 'https://repo.mot.dev/repository/maven-snapshots/'
    }
    maven {
        name = 'DaPorkchop_'
        url = 'https://maven.daporkchop.net/'
    }
    maven {
        name = 'NukkitX Snapshots'
        url = 'https://repo.nukkitx.com/snapshot'
    }
    mavenCentral()
}

dependencies {
    implementation "io.netty:netty-buffer:$nettyVersion"
    implementation ("net.daporkchop.lib:natives:$porklibVersion") {
        exclude group: 'io.netty'
    }
    implementation "com.hivemc.leveldb:leveldb-api:$leveldbVersion"
    implementation "com.hivemc.leveldb:leveldb:$leveldbVersion"
    implementation "com.google.guava:guava:$guavaVersion"
    implementation "org.iq80.snappy:snappy:$snappyVersion"

    testImplementation ("net.daporkchop.lib:encoding:$porklibVersion") {
        exclude group: 'io.netty'
    }
    testImplementation "junit:junit:$junitVersion"

    compileOnly "org.projectlombok:lombok:$lombokVersion"
    testCompileOnly "org.projectlombok:lombok:$lombokVersion"
    annotationProcessor "org.projectlombok:lombok:$lombokVersion"
    testAnnotationProcessor "org.projectlombok:lombok:$lombokVersion"
}

tasks.register('sourceJar', Jar) {
    from sourceSets.main.allSource
    archiveClassifier = 'sources'
}

publishing {
    repositories {
        if (mavenDeployUsername && mavenDeployPassword) {
            maven {
                credentials {
                    username = mavenDeployUsername
                    password = mavenDeployPassword
                }
                name = publishRepositoryName
                url = publishRepositoryUrl
            }
        }
    }

    publications {
        maven(MavenPublication) {
            groupId = project.group
            artifactId = 'leveldb-mcpe-jni'
            version = project.version

            from components.java

            artifact sourceJar
        }
    }
}

publish.dependsOn(publishToMavenLocal)
build.dependsOn(publish)

if (System.getProperty('os.name').toLowerCase().startsWith('windows')) {
    throw new IllegalStateException("You are running Windows, which is bad and you should feel bad.\nThis means that native libraries cannot be built.")
} else {
    tasks.register('compileNatives', Exec) {
        workingDir projectDir
        commandLine 'make', "-j${Runtime.runtime.availableProcessors()}"
    }

    compileJava.dependsOn compileNatives

    tasks.register('cleanNatives', Exec) {
        workingDir projectDir
        commandLine 'make', 'clean'
    }

    clean.dependsOn cleanNatives
}
