set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_OSX_ARCHITECTURES x86_64 CACHE STRING "" FORCE)

if(DEFINED ENV{DARWIN_MIN_VERSION})
    set(CMAKE_OSX_DEPLOYMENT_TARGET "$ENV{DARWIN_MIN_VERSION}" CACHE STRING "" FORCE)
else()
    set(CMAKE_OSX_DEPLOYMENT_TARGET "10.13" CACHE STRING "" FORCE)
endif()

find_program(CMAKE_C_COMPILER NAMES clang)
find_program(CMAKE_CXX_COMPILER NAMES clang++)
if(NOT CMAKE_C_COMPILER OR NOT CMAKE_CXX_COMPILER)
    message(FATAL_ERROR "Missing Apple clang toolchain. Install Xcode Command Line Tools.")
endif()

